//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.Serialization;
using SILPA.Comun;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;
using System.Data.SqlClient;
using System.Data.Common;
using System.Data;

namespace SILPA.AccesoDatos.Comunicacion
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 

    /// <comentarios/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/ComunicacionEE.xsd")]
    //[System.Xml.Serialization.XmlRootAttribute("comunicacionEE", Namespace = "http://tempuri.org/ComunicacionEE.xsd", IsNullable = false)]
    public partial class ComunicacionEEType: EntidadSerializable
    {

        private string numSilpaField;

        private string numExpedienteField;

        private string esperarRespuestaField;

        private EntidadExternaType[] entidadExternaField;

        private SolicitanteType[] listaSolicitantesField;


        //JMM
        private DateTime FechaDocField;
        private int Id_AA_OrigenField;
        private int Id_AA_DestinoField;
        private String str_AA_DestinoField;
        private int Id_TipoDocumentoField;
        private string NumeroDocumentoField;
        private decimal TiempoRespuestaField;

        
        private string descripcionField;
        public string Descripcion
        {
            get { return descripcionField; }
            set { descripcionField = value; }
        }

        public DateTime FechaDoc
        {
            get
            {
                return this.FechaDocField;
            }
            set
            {
                this.FechaDocField = value;
            }
        }

        public int Id_AA_Origen
        {
            get
            {
                return this.Id_AA_OrigenField;
            }
            set
            {
                this.Id_AA_OrigenField = value;
            }
        }

        public int Id_AA_Destino
        {
            get
            {
                return this.Id_AA_DestinoField;
            }
            set
            {
                this.Id_AA_DestinoField = value;
            }
        }


        public string Str_AA_Destino
        {
            get
            {
                return this.str_AA_DestinoField;
            }
            set
            {
                this.str_AA_DestinoField = value;
            }
        }

        public int Id_TipoDocumento
        {
            get
            {
                return this.Id_TipoDocumentoField;
            }
            set
            {
                this.Id_TipoDocumentoField = value;
            }
        }

        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }

        public decimal TiempoRespuesta
        {
            get
            {
                return this.TiempoRespuestaField;
            }
            set
            {
                this.TiempoRespuestaField = value;
            }
        }

        //

        /// <comentarios/>
        public string numSilpa
        {
            get
            {
                return this.numSilpaField;
            }
            set
            {
                this.numSilpaField = value;
            }
        }

        /// <comentarios/>
        public string numExpediente
        {
            get
            {
                return this.numExpedienteField;
            }
            set
            {
                this.numExpedienteField = value;
            }
        }

        /// <comentarios/>
        public string esperarRespuesta
        {
            get
            {
                return this.esperarRespuestaField;
            }
            set
            {
                this.esperarRespuestaField = value;
            }
        }

        
        /// <summary>
        /// HAVA:
        /// Determina si la actual comunicación es para 
        /// solicitar o no información adicional a un AA
        /// </summary>
        private bool solicitudInfoAA;
        public bool SolicitudInfoAA 
        {
            get { return this.solicitudInfoAA; }
            set { this.solicitudInfoAA = value; }
        }

        /// <summary>
        /// numero vital del proceso iniciado dentro del servicio al solicitar
        /// Primer proceso autogenerado.
        /// </summary>
        private string numeroVitalSolicitaInfoAA;
        public string NumeroVitalSolicitaInfoAA
        {
            get { return this.numeroVitalSolicitaInfoAA; }
            set { this.numeroVitalSolicitaInfoAA = value; }
        }


        /// <summary>
        /// hava:
        /// Número vital del segundo proceso generado en el servicio 
        /// al responder.
        /// Segundoproceso autogenerado
        /// </summary>
        private string numeroVitalRespondeInfoAA;
        public string NumeroVitalRespondeInfoAA
        {
            get { return this.numeroVitalRespondeInfoAA; }
            set { this.numeroVitalRespondeInfoAA = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("EntidadExternaType")]
        public EntidadExternaType[] EntidadExterna
        {
            get
            {
                return this.entidadExternaField;
            }
            set
            {
                this.entidadExternaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaSolicitantesType")]
        public SolicitanteType[] listaSolicitantes
        {
            get
            {
                return this.listaSolicitantesField;
            }
            set
            {
                this.listaSolicitantesField = value;
            }
        }

        /// <summary>
        /// contiene el listado de los documentos adjuntos.
        /// </summary>
        private ListaDocumentoAdjuntoType _lstDocumentosAdjuntos;
        public ListaDocumentoAdjuntoType ListaDocumentoAdjuntoType
        {
            get { return _lstDocumentosAdjuntos; }
            set { _lstDocumentosAdjuntos = value; }
        }


        #region Método para listar los documentos adjuntos

        /// <summary>
        /// Carga los archvivos adjuntos en el objeto de documentos
        /// </summary>
        /// <param name="lstNombresArchivo">List(string)</param>
        /// <param name="lstBytesArchivo">List(byte[])</param>
        public void DocumentosAdjuntos
            (
                List<string> lstNombresArchivo,
                List<Byte[]> lstBytesArchivo
            )
        {
            this._lstDocumentosAdjuntos = new ListaDocumentoAdjuntoType();
            /// Vector que contiene los
            this._lstDocumentosAdjuntos.ListaDocumento = new documentoAdjuntoType[lstNombresArchivo.Count];

            int i = 0;
            foreach (string archivo in lstNombresArchivo)
            {
                documentoAdjuntoType documento = new documentoAdjuntoType();
                documento.nombreArchivo = archivo;
                documento.bytes = lstBytesArchivo[i];
                this._lstDocumentosAdjuntos.ListaDocumento.SetValue(documento, i);
                i++;
            }
        }

        /// <summary>
        /// Hava:
        /// Devuelve el identificador del solicitante que solicita la informacion adicional a la AA
        /// </summary>
        public long ObtenerFuncionarioInciaProceso(int intIdAA, Configuracion objConfiguracion) 
        {
            long result =0;
            try
            {
                SqlDatabase db = new SqlDatabase(objConfiguracion.SilpaCnx.ToString());
                object[] parametros = new object[] { intIdAA , 0 };
                DbCommand cmd = db.GetStoredProcCommand("FSI_OBTENER_FUNCIONARIO_SOLICITA_AA", parametros);
                int i = db.ExecuteNonQuery(cmd);

                result = long.Parse(db.GetParameterValue(cmd, "ID_FUNCIONARIO").ToString());

                return result;
            }
            catch (SqlException sqle)
            {
                throw new Exception(sqle.Message);
            }
        }

        /// <summary>
        /// hava
        /// Registra los datos de una comunicaciónEE
        /// para mantener la relacion de los expedientes y silpa generados en el proceso
        /// </summary>
        public void RegistrarComunicacion(int idAA, int intSolicita, Configuracion objConfiguracion) 
        {
            object result = null;
            try
            {
                SqlDatabase db = new SqlDatabase(objConfiguracion.SilpaCnx.ToString());
                object[] parametros = new object[] { idAA, this.numSilpaField, this.numExpedienteField, this.NumeroDocumento, this.numeroVitalSolicitaInfoAA, this.numeroVitalRespondeInfoAA, intSolicita };
                DbCommand cmd = db.GetStoredProcCommand("CEE_REGISTRAR_COMUNICACION_AA", parametros);
                int i = db.ExecuteNonQuery(cmd);
            }
            catch (SqlException sqle)
            {
                throw new Exception(sqle.Message);
            }
        }


        /// <summary>
        /// Hava:
        /// </summary>
        /// <param name="TramiteSolicitaInfoAA">identificador del tipo de trámite</param>
        /// <returns>long identificador del trámite</returns>
        public long ObtenerTipoTramiteIniciaProceso(bool responde, Configuracion objConfiguracion) 
        {
            long result = -1;
            string parametro = string.Empty;

            if (!responde)   /// solicita información
                parametro = "TRAMITE_SOLICITUD_INFO_AA";  
            else
                parametro = "TRAMITE_RESPUESTA_INFO_AA";  

            try
            {

                SqlDatabase db = new SqlDatabase(objConfiguracion.SilpaCnx.ToString());
                object[] parametros = new object[] { -1, parametro };
                DbCommand cmd = db.GetStoredProcCommand("dbo.GEN_LISTAR_PARAMETROS", parametros);
                DataSet ds = db.ExecuteDataSet(cmd);

                if (ds != null) 
                {
                    if (ds.Tables.Count > 0) 
                    {
                        result = long.Parse(ds.Tables[0].Rows[0]["PARAMETRO"].ToString());
                    }
                }

                return result;
            }
            catch (SqlException sqle)
            {
                throw new Exception(sqle.Message);
            }
    
        }

        #endregion
    }

    /// <comentarios/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/ComunicacionEE.xsd")]
    //[System.Xml.Serialization.XmlRootAttribute("EntidadExterna", Namespace = "http://tempuri.org/ComunicacionEE.xsd", IsNullable = false)]
    public partial class EntidadExternaType
    {

        private string nombreField;

        private string correoElectronicoField;

        /// <comentarios/>
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <comentarios/>
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
    }

    /// <comentarios/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/ComunicacionEE.xsd")]
    public partial class SolicitanteType
    {

        private string nombreField;

        private string correoField;

        /// <comentarios/>
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }

        /// <comentarios/>
        public string Correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
    }

}



