//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4200
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.4200.
// 
#pragma warning disable 1591

namespace AppRadicacion.EnviarDatosSolicitud {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSPQ03Soap", Namespace="http://tempuri.org/")]
    public partial class WSPQ03 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecibirDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmitirDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDatosAdjuntosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarDatosRadicacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSPQ03() {
            this.Url = global::AppRadicacion.Properties.Settings.Default.AppRadicacion_EnviarDatosSolicitud_WSPQ03;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecibirDocumentoCompletedEventHandler RecibirDocumentoCompleted;
        
        /// <remarks/>
        public event EmitirDocumentoCompletedEventHandler EmitirDocumentoCompleted;
        
        /// <remarks/>
        public event ObtenerDatosAdjuntosCompletedEventHandler ObtenerDatosAdjuntosCompleted;
        
        /// <remarks/>
        public event EnviarDatosRadicacionCompletedEventHandler EnviarDatosRadicacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/[RecibirActoAdministrativoEIA-01]", RequestElementName="[RecibirActoAdministrativoEIA-01]", RequestNamespace="http://tempuri.org/", ResponseElementName="[RecibirActoAdministrativoEIA-01]Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("[RecibirActoAdministrativoEIA-01]Result")]
        public bool RecibirDocumento(string documentoXML) {
            object[] results = this.Invoke("RecibirDocumento", new object[] {
                        documentoXML});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RecibirDocumentoAsync(string documentoXML) {
            this.RecibirDocumentoAsync(documentoXML, null);
        }
        
        /// <remarks/>
        public void RecibirDocumentoAsync(string documentoXML, object userState) {
            if ((this.RecibirDocumentoOperationCompleted == null)) {
                this.RecibirDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecibirDocumentoOperationCompleted);
            }
            this.InvokeAsync("RecibirDocumento", new object[] {
                        documentoXML}, this.RecibirDocumentoOperationCompleted, userState);
        }
        
        private void OnRecibirDocumentoOperationCompleted(object arg) {
            if ((this.RecibirDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecibirDocumentoCompleted(this, new RecibirDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/[CU-GN-01 Emitir Documento]", RequestElementName="[CU-GN-01 Emitir Documento]", RequestNamespace="http://tempuri.org/", ResponseElementName="[CU-GN-01 Emitir Documento]Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("[CU-GN-01 Emitir Documento]Result")]
        public string EmitirDocumento(string actoAdm) {
            object[] results = this.Invoke("EmitirDocumento", new object[] {
                        actoAdm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EmitirDocumentoAsync(string actoAdm) {
            this.EmitirDocumentoAsync(actoAdm, null);
        }
        
        /// <remarks/>
        public void EmitirDocumentoAsync(string actoAdm, object userState) {
            if ((this.EmitirDocumentoOperationCompleted == null)) {
                this.EmitirDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmitirDocumentoOperationCompleted);
            }
            this.InvokeAsync("EmitirDocumento", new object[] {
                        actoAdm}, this.EmitirDocumentoOperationCompleted, userState);
        }
        
        private void OnEmitirDocumentoOperationCompleted(object arg) {
            if ((this.EmitirDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmitirDocumentoCompleted(this, new EmitirDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDatosAdjuntos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerDatosAdjuntos(string strXmlDatos) {
            object[] results = this.Invoke("ObtenerDatosAdjuntos", new object[] {
                        strXmlDatos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDatosAdjuntosAsync(string strXmlDatos) {
            this.ObtenerDatosAdjuntosAsync(strXmlDatos, null);
        }
        
        /// <remarks/>
        public void ObtenerDatosAdjuntosAsync(string strXmlDatos, object userState) {
            if ((this.ObtenerDatosAdjuntosOperationCompleted == null)) {
                this.ObtenerDatosAdjuntosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDatosAdjuntosOperationCompleted);
            }
            this.InvokeAsync("ObtenerDatosAdjuntos", new object[] {
                        strXmlDatos}, this.ObtenerDatosAdjuntosOperationCompleted, userState);
        }
        
        private void OnObtenerDatosAdjuntosOperationCompleted(object arg) {
            if ((this.ObtenerDatosAdjuntosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDatosAdjuntosCompleted(this, new ObtenerDatosAdjuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/[EnviarDatosRadicacion]", RequestElementName="[EnviarDatosRadicacion]", RequestNamespace="http://tempuri.org/", ResponseElementName="[EnviarDatosRadicacion]Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("[EnviarDatosRadicacion]Result")]
        public string EnviarDatosRadicacion(string strXmlDatos) {
            object[] results = this.Invoke("EnviarDatosRadicacion", new object[] {
                        strXmlDatos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarDatosRadicacionAsync(string strXmlDatos) {
            this.EnviarDatosRadicacionAsync(strXmlDatos, null);
        }
        
        /// <remarks/>
        public void EnviarDatosRadicacionAsync(string strXmlDatos, object userState) {
            if ((this.EnviarDatosRadicacionOperationCompleted == null)) {
                this.EnviarDatosRadicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarDatosRadicacionOperationCompleted);
            }
            this.InvokeAsync("EnviarDatosRadicacion", new object[] {
                        strXmlDatos}, this.EnviarDatosRadicacionOperationCompleted, userState);
        }
        
        private void OnEnviarDatosRadicacionOperationCompleted(object arg) {
            if ((this.EnviarDatosRadicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarDatosRadicacionCompleted(this, new EnviarDatosRadicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void RecibirDocumentoCompletedEventHandler(object sender, RecibirDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecibirDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecibirDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void EmitirDocumentoCompletedEventHandler(object sender, EmitirDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmitirDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmitirDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ObtenerDatosAdjuntosCompletedEventHandler(object sender, ObtenerDatosAdjuntosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDatosAdjuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDatosAdjuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void EnviarDatosRadicacionCompletedEventHandler(object sender, EnviarDatosRadicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarDatosRadicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarDatosRadicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591