//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using SILPA.Comun;

namespace SILPA.AccesoDatos.Sancionatorio

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
{
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/Sancionatorio.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Sancionatorio", Namespace = "http://tempuri.org/Sancionatorio.xsd", IsNullable = false)]


    public partial class SancionatorioIdentity : EntidadSerializable
    {

        private string numeroSilpaField;

        private string numeroRadicacionField;

        private string mensajeField;

        /// <comentarios/>
        public string NumeroSilpa
        {
            get
            {
                return this.numeroSilpaField;
            }
            set
            {
                this.numeroSilpaField = value;
            }
        }

        /// <comentarios/>
        public string NumeroRadicacion
        {
            get
            {
                return this.numeroRadicacionField;
            }
            set
            {
                this.numeroRadicacionField = value;
            }
        }

        /// <comentarios/>
        public string Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
}
