//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/ConstulaEstadoNotificacion.xsd")]
[System.Xml.Serialization.XmlRootAttribute("Consulta", Namespace="http://tempuri.org/ConstulaEstadoNotificacion.xsd", IsNullable=false)]
public partial class NotificacionConsultaType {
    
    private string numProcesoAdministracionField;
    
    private string numActoAdministrativoNotificacionField;

    private string numTipoDocumentoField;

    private string numIdAAField;
    
    /// <remarks/>
    public string numProcesoAdministracion {
        get {
            return this.numProcesoAdministracionField;
        }
        set {
            this.numProcesoAdministracionField = value;
        }
    }
    
    /// <remarks/>
    public string numActoAdministrativoNotificacion {
        get {
            return this.numActoAdministrativoNotificacionField;
        }
        set {
            this.numActoAdministrativoNotificacionField = value;
        }
    }

    public string numTipoDocumento
    {
        get
        {
            return this.numTipoDocumentoField;
        }
        set
        {
            this.numTipoDocumentoField = value;
        }
    }

    public string numIdAA
    {
        get
        { return this.numIdAAField; }
        set { this.numIdAAField = value; }
    }
}
