//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=2.0.50727.42.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SancionRUIA.xsd")]
[System.Xml.Serialization.XmlRootAttribute("listasRuia", Namespace="http://tempuri.org/SancionRUIA.xsd", IsNullable=false)]
public partial class ListasSancionType {
    
    private TipoFaltaType[] listaFaltasField;
    
    private OpcionTipoSancionType[] listaOpcionesField;
    
    private TipoSancionType[] listaTipoSancionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("listaFaltas")]
    public TipoFaltaType[] listaFaltas {
        get {
            return this.listaFaltasField;
        }
        set {
            this.listaFaltasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("listaOpciones")]
    public OpcionTipoSancionType[] listaOpciones {
        get {
            return this.listaOpcionesField;
        }
        set {
            this.listaOpcionesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("listaTipoSancion")]
    public TipoSancionType[] listaTipoSancion {
        get {
            return this.listaTipoSancionField;
        }
        set {
            this.listaTipoSancionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SancionRUIA.xsd")]
public partial class TipoFaltaType {
    
    private int idTipoFaltaField;
    
    private string nombreTipoFaltaField;
    
    /// <comentarios/>
    public int idTipoFalta {
        get {
            return this.idTipoFaltaField;
        }
        set {
            this.idTipoFaltaField = value;
        }
    }
    
    /// <comentarios/>
    public string nombreTipoFalta {
        get {
            return this.nombreTipoFaltaField;
        }
        set {
            this.nombreTipoFaltaField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SancionRUIA.xsd")]
public partial class TipoSancionType {
    
    private int idTipoSancionField;
    
    private string nombreTipoSancionField;
    
    /// <comentarios/>
    public int idTipoSancion {
        get {
            return this.idTipoSancionField;
        }
        set {
            this.idTipoSancionField = value;
        }
    }
    
    /// <comentarios/>
    public string nombreTipoSancion {
        get {
            return this.nombreTipoSancionField;
        }
        set {
            this.nombreTipoSancionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SancionRUIA.xsd")]
public partial class OpcionTipoSancionType {
    
    private int idOpcionSancionField;
    
    private string nombreOpcionSancionField;
    
    /// <comentarios/>
    public int idOpcionSancion {
        get {
            return this.idOpcionSancionField;
        }
        set {
            this.idOpcionSancionField = value;
        }
    }
    
    /// <comentarios/>
    public string nombreOpcionSancion {
        get {
            return this.nombreOpcionSancionField;
        }
        set {
            this.nombreOpcionSancionField = value;
        }
    }
}
