//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftManagement.CorreoElectronico {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftManagement.CorreoElectronico.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30.
        /// </summary>
        internal static string DiasInhabilitar {
            get {
                return ResourceManager.GetString("DiasInhabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMSP_CORREO_ELECTRONICO_ACTUALIZAR.
        /// </summary>
        internal static string ProcedimientoActualizarCorreo {
            get {
                return ResourceManager.GetString("ProcedimientoActualizarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMSP_CORREO_CONSULTAR_PENDIENTES_ENVIO.
        /// </summary>
        internal static string ProcedimientoConsultarCorreosEnviar {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarCorreosEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMSP_CORREO_PLANTILLA_CONSULTAR.
        /// </summary>
        internal static string ProcedimientoConsultarPlantilla {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMSP_CORREO_SERVIDOR_CONSULTAR.
        /// </summary>
        internal static string ProcedimientoConsultarServidor {
            get {
                return ResourceManager.GetString("ProcedimientoConsultarServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMSP_CORREO_ELECTRONICO_INSERTAR.
        /// </summary>
        internal static string ProcedimientoInsertarCorreo {
            get {
                return ResourceManager.GetString("ProcedimientoInsertarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMSP_CORREO_ELECTRONICO_INSERTAR_INHABILITADO.
        /// </summary>
        internal static string ProcedimientoInsertarCorreoInhabilitado {
            get {
                return ResourceManager.GetString("ProcedimientoInsertarCorreoInhabilitado", resourceCulture);
            }
        }
    }
}
