//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <comentarios/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Salvoconducto.xsd")]
//[System.Xml.Serialization.XmlRootAttribute("Salvoconducto", Namespace="http://tempuri.org/Salvoconducto.xsd", IsNullable=false)]
using System;
using System.Collections.Generic;
using System.Text;
using SILPA.Comun;


namespace SILPA.AccesoDatos.RecursoIdentity
{
    public partial class RecursosIdentity: EntidadSerializable
    {

        private int recursoIdField;

        private int tipoRecursoField;

        private string nombreRecursoField;

        private string descripcionRecursoField;

        private double recursoCantidadField;

        private int AreaHidrograficaIdField;

        private int ZonaHidrograficaIdField;

        private int SubZonaHidrograficaIdField;

        private string nombreCientificoField;

        /// <comentarios/>
        public int RecursoId
        {
            get
            {
                return this.recursoIdField;
            }
            set
            {
                this.recursoIdField = value;
            }
        }


        /// <comentarios/>
        public int TipoRecurso
        {
            get
            {
                return this.tipoRecursoField;
            }
            set
            {
                this.tipoRecursoField = value;
            }
        }

        /// <comentarios/>
        public string NombreRecurso
        {
            get
            {
                return this.nombreRecursoField;
            }
            set
            {
                this.nombreRecursoField = value;
            }
        }

        /// <comentarios/>
        public string DescripcionRecurso
        {
            get
            {
                return this.descripcionRecursoField;
            }
            set
            {
                this.descripcionRecursoField = value;
            }
        }

        /// <comentarios/>
        public double CantidadRecurso
        {
            get
            {
                return this.recursoCantidadField;
            }
            set
            {
                this.recursoCantidadField = value;
            }
        }


        /// <comentarios/>
        public int AreaHidrograficaId
        {
            get
            {
                return this.AreaHidrograficaIdField;
            }
            set
            {
                this.AreaHidrograficaIdField = value;
            }
        }


        /// <comentarios/>
        public int ZonaHidrograficaId
        {
            get
            {
                return this.ZonaHidrograficaIdField;
            }
            set
            {
                this.ZonaHidrograficaIdField = value;
            }
        }
        /// <comentarios/>
        public int SubZonaHidrograficaId
        {
            get
            {
                return this.SubZonaHidrograficaIdField;
            }
            set
            {
                this.SubZonaHidrograficaIdField = value;
            }
        }

        public string NombreCientifico
        {
            get
            {
                return this.nombreCientificoField;
            }
            set
            {
                this.nombreCientificoField = value;
            }
        }
    }   
}
