//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <comentarios/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/Salvoconducto.xsd")]
//[System.Xml.Serialization.XmlRootAttribute("Salvoconducto", Namespace="http://tempuri.org/Salvoconducto.xsd", IsNullable=false)]
using System;
using System.Collections.Generic;
using System.Text;
using SILPA.Comun;


namespace SILPA.AccesoDatos.Salvoconducto
{
    public partial class SalvoconductoIdentity: EntidadSerializable
    {

        private int recursoRelacionadoField;

        private int _idSalvoconducto;

        private string numeroSilpaField;

        private string numeroExpedienteField;

        private string tipoSalvoconductoField;

        private int idTipoSalvoconductoField;

        private string numeroSalvoconductoField;

        private string numeroSalvoconductoAnteriorField;

        private string fechaDesdeField;

        private string tipoRecursoFloraField;

        private int? idTipoRecursoFloraField;

        private string rutaField;

        private string fechaHastaField;

        private EspecimenIdentity[] especimenField;

        private TransporteIdentity[] transporteField;

        public int idSalvoconducto
        {
            get
            {
                return this._idSalvoconducto;
            }
            set
            {
                this._idSalvoconducto = value;
            }
        }

        public int RecursoRelacionado
        {
            get
            {
                return this.recursoRelacionadoField;
            }
            set
            {
                this.recursoRelacionadoField = value;
            }
        }

        /// <comentarios/>
        public string NumeroSilpa
        {
            get
            {
                return this.numeroSilpaField;
            }
            set
            {
                this.numeroSilpaField = value;
            }
        }

        /// <comentarios/>
        public string NumeroExpediente
        {
            get
            {
                return this.numeroExpedienteField;
            }
            set
            {
                this.numeroExpedienteField = value;
            }
        }

        /// <comentarios/>
        public string TipoSalvoconducto
        {
            get
            {
                return this.tipoSalvoconductoField;
            }
            set
            {
                this.tipoSalvoconductoField = value;
            }
        }

        /// <comentarios/>
        public int IdTipoSalvoconducto
        {
            get
            {
                return this.idTipoSalvoconductoField;
            }
            set
            {
                this.idTipoSalvoconductoField = value;
            }
        }

        /// <comentarios/>
        public string NumeroSalvoconducto
        {
            get
            {
                return this.numeroSalvoconductoField;
            }
            set
            {
                this.numeroSalvoconductoField = value;
            }
        }

        /// <comentarios/>
        public string NumeroSalvoconductoAnterior
        {
            get
            {
                return this.numeroSalvoconductoAnteriorField;
            }
            set
            {
                this.numeroSalvoconductoAnteriorField = value;
            }
        }

        /// <comentarios/>
        public string FechaDesde
        {
            get
            {
                return this.fechaDesdeField;
            }
            set
            {
                this.fechaDesdeField = value;
            }
        }

        /// <comentarios/>
        public string TipoRecursoFlora
        {
            get
            {
                return this.tipoRecursoFloraField;
            }
            set
            {
                this.tipoRecursoFloraField = value;
            }
        }

        /// <comentarios/>
        public int? IdTipoRecursoFlora
        {
            get
            {
                return this.idTipoRecursoFloraField;
            }
            set
            {
                this.idTipoRecursoFloraField = value;
            }
        }

        /// <comentarios/>
        public string FechaHasta
        {
            get
            {
                return this.fechaHastaField;
            }
            set
            {
                this.fechaHastaField = value;
            }
        }

        /// <comentarios/>
        public string Ruta
        {
            get
            {
                return this.rutaField;
            }
            set
            {
                this.rutaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("especimen")]
        public EspecimenIdentity[] especimen
        {
            get
            {
                return this.especimenField;
            }
            set
            {
                this.especimenField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("transporte")]
        public TransporteIdentity[] transporte
        {
            get
            {
                return this.transporteField;
            }
            set
            {
                this.transporteField = value;
            }
        }
    }   
}
