//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", ConfigurationName="WSRegistrarAprovechamientoIDEAM.RegistrarAprovechamientoPortType")]
    public interface RegistrarAprovechamientoPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (AprovechamientoRequest) del mensaje guardarAprovechamientoRequest no coincide con el valor predeterminado (guardarAprovechamiento)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoResponse guardarAprovechamiento(SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class Auditoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sistemaSolicitudField;
        
        private string autoridadAmbientalField;
        
        private string codigoNumeroTransaccionField;
        
        private string dependenciaField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SistemaSolicitud {
            get {
                return this.sistemaSolicitudField;
            }
            set {
                this.sistemaSolicitudField = value;
                this.RaisePropertyChanged("SistemaSolicitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AutoridadAmbiental {
            get {
                return this.autoridadAmbientalField;
            }
            set {
                this.autoridadAmbientalField = value;
                this.RaisePropertyChanged("AutoridadAmbiental");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CodigoNumeroTransaccion {
            get {
                return this.codigoNumeroTransaccionField;
            }
            set {
                this.codigoNumeroTransaccionField = value;
                this.RaisePropertyChanged("CodigoNumeroTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Dependencia {
            get {
                return this.dependenciaField;
            }
            set {
                this.dependenciaField = value;
                this.RaisePropertyChanged("Dependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class Especie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoNombreCientificoField;
        
        private string nombreComunField;
        
        private string codigoClaseRecursoField;
        
        private string codigoTipoProductoField;
        
        private string volumenBrutoOtorgadoMaderableField;
        
        private string volumenBrutoOtorgadoNoMaderableField;
        
        private string codigoUnidadMedidaField;
        
        private string observacionesField;
        
        private string diametroAlturaPechoField;
        
        private string alturaComercialField;
        
        private string tratamientoSilviculturaAsignadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoNombreCientifico {
            get {
                return this.codigoNombreCientificoField;
            }
            set {
                this.codigoNombreCientificoField = value;
                this.RaisePropertyChanged("CodigoNombreCientifico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NombreComun {
            get {
                return this.nombreComunField;
            }
            set {
                this.nombreComunField = value;
                this.RaisePropertyChanged("NombreComun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CodigoClaseRecurso {
            get {
                return this.codigoClaseRecursoField;
            }
            set {
                this.codigoClaseRecursoField = value;
                this.RaisePropertyChanged("CodigoClaseRecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CodigoTipoProducto {
            get {
                return this.codigoTipoProductoField;
            }
            set {
                this.codigoTipoProductoField = value;
                this.RaisePropertyChanged("CodigoTipoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string VolumenBrutoOtorgadoMaderable {
            get {
                return this.volumenBrutoOtorgadoMaderableField;
            }
            set {
                this.volumenBrutoOtorgadoMaderableField = value;
                this.RaisePropertyChanged("VolumenBrutoOtorgadoMaderable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string VolumenBrutoOtorgadoNoMaderable {
            get {
                return this.volumenBrutoOtorgadoNoMaderableField;
            }
            set {
                this.volumenBrutoOtorgadoNoMaderableField = value;
                this.RaisePropertyChanged("VolumenBrutoOtorgadoNoMaderable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CodigoUnidadMedida {
            get {
                return this.codigoUnidadMedidaField;
            }
            set {
                this.codigoUnidadMedidaField = value;
                this.RaisePropertyChanged("CodigoUnidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("Observaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string DiametroAlturaPecho {
            get {
                return this.diametroAlturaPechoField;
            }
            set {
                this.diametroAlturaPechoField = value;
                this.RaisePropertyChanged("DiametroAlturaPecho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string AlturaComercial {
            get {
                return this.alturaComercialField;
            }
            set {
                this.alturaComercialField = value;
                this.RaisePropertyChanged("AlturaComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TratamientoSilviculturaAsignado {
            get {
                return this.tratamientoSilviculturaAsignadoField;
            }
            set {
                this.tratamientoSilviculturaAsignadoField = value;
                this.RaisePropertyChanged("TratamientoSilviculturaAsignado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class Vertice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string latitudField;
        
        private string longitudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("Latitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("Longitud");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class InfoLugarAprovechamiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombrePredioField;
        
        private string direccionPredioField;
        
        private string veredaField;
        
        private string corregimientoField;
        
        private string codigoDepartamentoField;
        
        private string codigoMunicipioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NombrePredio {
            get {
                return this.nombrePredioField;
            }
            set {
                this.nombrePredioField = value;
                this.RaisePropertyChanged("NombrePredio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DireccionPredio {
            get {
                return this.direccionPredioField;
            }
            set {
                this.direccionPredioField = value;
                this.RaisePropertyChanged("DireccionPredio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Vereda {
            get {
                return this.veredaField;
            }
            set {
                this.veredaField = value;
                this.RaisePropertyChanged("Vereda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Corregimiento {
            get {
                return this.corregimientoField;
            }
            set {
                this.corregimientoField = value;
                this.RaisePropertyChanged("Corregimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CodigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
                this.RaisePropertyChanged("CodigoDepartamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
                this.RaisePropertyChanged("CodigoMunicipio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class InfoGralTramite : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroActoAdministrativoAprovechamientoField;
        
        private string fechaExpedicionActoAdministrativoField;
        
        private string fechaFinalizacionActoAdministrativoField;
        
        private string codigoClaseAprovechamientoField;
        
        private string codigoUbicacionArbolAisladoField;
        
        private string codigoFormaOtorgaAprovechamientoField;
        
        private string areaTotalOtorgadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NumeroActoAdministrativoAprovechamiento {
            get {
                return this.numeroActoAdministrativoAprovechamientoField;
            }
            set {
                this.numeroActoAdministrativoAprovechamientoField = value;
                this.RaisePropertyChanged("NumeroActoAdministrativoAprovechamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FechaExpedicionActoAdministrativo {
            get {
                return this.fechaExpedicionActoAdministrativoField;
            }
            set {
                this.fechaExpedicionActoAdministrativoField = value;
                this.RaisePropertyChanged("FechaExpedicionActoAdministrativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string FechaFinalizacionActoAdministrativo {
            get {
                return this.fechaFinalizacionActoAdministrativoField;
            }
            set {
                this.fechaFinalizacionActoAdministrativoField = value;
                this.RaisePropertyChanged("FechaFinalizacionActoAdministrativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CodigoClaseAprovechamiento {
            get {
                return this.codigoClaseAprovechamientoField;
            }
            set {
                this.codigoClaseAprovechamientoField = value;
                this.RaisePropertyChanged("CodigoClaseAprovechamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CodigoUbicacionArbolAislado {
            get {
                return this.codigoUbicacionArbolAisladoField;
            }
            set {
                this.codigoUbicacionArbolAisladoField = value;
                this.RaisePropertyChanged("CodigoUbicacionArbolAislado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CodigoFormaOtorgaAprovechamiento {
            get {
                return this.codigoFormaOtorgaAprovechamientoField;
            }
            set {
                this.codigoFormaOtorgaAprovechamientoField = value;
                this.RaisePropertyChanged("CodigoFormaOtorgaAprovechamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AreaTotalOtorgada {
            get {
                return this.areaTotalOtorgadaField;
            }
            set {
                this.areaTotalOtorgadaField = value;
                this.RaisePropertyChanged("AreaTotalOtorgada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class InfoUsuarioRecurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoTipoPersonaField;
        
        private string codigoTipoIdentificacionField;
        
        private string identificacionField;
        
        private string razonSocialField;
        
        private string primerNombreField;
        
        private string segundoNombreField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private string correoElectronicoField;
        
        private string telefonoFijoField;
        
        private string celularField;
        
        private string direccionField;
        
        private string codigoDepartamentoField;
        
        private string codigoMunicipioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoTipoPersona {
            get {
                return this.codigoTipoPersonaField;
            }
            set {
                this.codigoTipoPersonaField = value;
                this.RaisePropertyChanged("CodigoTipoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CodigoTipoIdentificacion {
            get {
                return this.codigoTipoIdentificacionField;
            }
            set {
                this.codigoTipoIdentificacionField = value;
                this.RaisePropertyChanged("CodigoTipoIdentificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
                this.RaisePropertyChanged("Identificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("RazonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PrimerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
                this.RaisePropertyChanged("PrimerNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SegundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
                this.RaisePropertyChanged("SegundoNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string PrimerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("PrimerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string SegundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("SegundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CorreoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("CorreoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TelefonoFijo {
            get {
                return this.telefonoFijoField;
            }
            set {
                this.telefonoFijoField = value;
                this.RaisePropertyChanged("TelefonoFijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
                this.RaisePropertyChanged("Celular");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CodigoDepartamento {
            get {
                return this.codigoDepartamentoField;
            }
            set {
                this.codigoDepartamentoField = value;
                this.RaisePropertyChanged("CodigoDepartamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CodigoMunicipio {
            get {
                return this.codigoMunicipioField;
            }
            set {
                this.codigoMunicipioField = value;
                this.RaisePropertyChanged("CodigoMunicipio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
    public partial class InfoGralAA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoAutoridadField;
        
        private string dependenciaField;
        
        private string funcionarioField;
        
        private string correoField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CodigoAutoridad {
            get {
                return this.codigoAutoridadField;
            }
            set {
                this.codigoAutoridadField = value;
                this.RaisePropertyChanged("CodigoAutoridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Dependencia {
            get {
                return this.dependenciaField;
            }
            set {
                this.dependenciaField = value;
                this.RaisePropertyChanged("Dependencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Funcionario {
            get {
                return this.funcionarioField;
            }
            set {
                this.funcionarioField = value;
                this.RaisePropertyChanged("Funcionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AprovechamientoRequest", WrapperNamespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", IsWrapped=true)]
    public partial class guardarAprovechamientoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/")]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Auditoria Auditoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoGralAA InfoGralAA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoUsuarioRecurso InfoUsuarioRecurso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoGralTramite InfoGralTramite;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoLugarAprovechamiento InfoLugarAprovechamiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=4)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Vertices", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Vertice[] Poligono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=5)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EspeciesAprovechadas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Especie[] InfoEspecieAprovechada;
        
        public guardarAprovechamientoRequest() {
        }
        
        public guardarAprovechamientoRequest(SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Auditoria Auditoria, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoGralAA InfoGralAA, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoUsuarioRecurso InfoUsuarioRecurso, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoGralTramite InfoGralTramite, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoLugarAprovechamiento InfoLugarAprovechamiento, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Vertice[] Poligono, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Especie[] InfoEspecieAprovechada) {
            this.Auditoria = Auditoria;
            this.InfoGralAA = InfoGralAA;
            this.InfoUsuarioRecurso = InfoUsuarioRecurso;
            this.InfoGralTramite = InfoGralTramite;
            this.InfoLugarAprovechamiento = InfoLugarAprovechamiento;
            this.Poligono = Poligono;
            this.InfoEspecieAprovechada = InfoEspecieAprovechada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AprovechamientoResponse", WrapperNamespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", IsWrapped=true)]
    public partial class guardarAprovechamientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Exitoso;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("MensajeError", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] MensajeError;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/snif/registraraprovechamiento/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificadorCargue;
        
        public guardarAprovechamientoResponse() {
        }
        
        public guardarAprovechamientoResponse(bool Exitoso, string CodigoError, string[] MensajeError, string IdentificadorCargue) {
            this.Exitoso = Exitoso;
            this.CodigoError = CodigoError;
            this.MensajeError = MensajeError;
            this.IdentificadorCargue = IdentificadorCargue;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrarAprovechamientoPortTypeChannel : SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.RegistrarAprovechamientoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarAprovechamientoPortTypeClient : System.ServiceModel.ClientBase<SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.RegistrarAprovechamientoPortType>, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.RegistrarAprovechamientoPortType {
        
        public RegistrarAprovechamientoPortTypeClient() {
        }
        
        public RegistrarAprovechamientoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrarAprovechamientoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrarAprovechamientoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrarAprovechamientoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoResponse SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.RegistrarAprovechamientoPortType.guardarAprovechamiento(SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoRequest request) {
            return base.Channel.guardarAprovechamiento(request);
        }
        
        public bool guardarAprovechamiento(SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Auditoria Auditoria, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoGralAA InfoGralAA, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoUsuarioRecurso InfoUsuarioRecurso, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoGralTramite InfoGralTramite, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.InfoLugarAprovechamiento InfoLugarAprovechamiento, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Vertice[] Poligono, SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.Especie[] InfoEspecieAprovechada, out string CodigoError, out string[] MensajeError, out string IdentificadorCargue) {
            SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoRequest inValue = new SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoRequest();
            inValue.Auditoria = Auditoria;
            inValue.InfoGralAA = InfoGralAA;
            inValue.InfoUsuarioRecurso = InfoUsuarioRecurso;
            inValue.InfoGralTramite = InfoGralTramite;
            inValue.InfoLugarAprovechamiento = InfoLugarAprovechamiento;
            inValue.Poligono = Poligono;
            inValue.InfoEspecieAprovechada = InfoEspecieAprovechada;
            SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.guardarAprovechamientoResponse retVal = ((SILPA.LogicaNegocio.WSRegistrarAprovechamientoIDEAM.RegistrarAprovechamientoPortType)(this)).guardarAprovechamiento(inValue);
            CodigoError = retVal.CodigoError;
            MensajeError = retVal.MensajeError;
            IdentificadorCargue = retVal.IdentificadorCargue;
            return retVal.Exitoso;
        }
    }
}
