//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros", ConfigurationName="WSConsultarEspeciesIDEAM.snifconpar_ptt")]
    public interface snifconpar_ptt {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarEspecies no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="consultarEspecies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesResponse consultarEspecies(SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros")]
    public partial class Auditoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sistemaSolicitudField;
        
        private string fechaHoraSolicitudField;
        
        private string ipSolicitudField;
        
        private string autoridadAmbientalField;
        
        private string codigoNumeroTransaccionField;
        
        private string dependenciaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SistemaSolicitud {
            get {
                return this.sistemaSolicitudField;
            }
            set {
                this.sistemaSolicitudField = value;
                this.RaisePropertyChanged("SistemaSolicitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FechaHoraSolicitud {
            get {
                return this.fechaHoraSolicitudField;
            }
            set {
                this.fechaHoraSolicitudField = value;
                this.RaisePropertyChanged("FechaHoraSolicitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IpSolicitud {
            get {
                return this.ipSolicitudField;
            }
            set {
                this.ipSolicitudField = value;
                this.RaisePropertyChanged("IpSolicitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AutoridadAmbiental {
            get {
                return this.autoridadAmbientalField;
            }
            set {
                this.autoridadAmbientalField = value;
                this.RaisePropertyChanged("AutoridadAmbiental");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CodigoNumeroTransaccion {
            get {
                return this.codigoNumeroTransaccionField;
            }
            set {
                this.codigoNumeroTransaccionField = value;
                this.RaisePropertyChanged("CodigoNumeroTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Dependencia {
            get {
                return this.dependenciaField;
            }
            set {
                this.dependenciaField = value;
                this.RaisePropertyChanged("Dependencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros")]
    public partial class Parametro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros")]
    public partial class ParametrosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool exitosoField;
        
        private bool exitosoFieldSpecified;
        
        private string codigoErrorField;
        
        private string[] mensajeErrorField;
        
        private string identificadorConsultaField;
        
        private Parametro[] parametroField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Exitoso {
            get {
                return this.exitosoField;
            }
            set {
                this.exitosoField = value;
                this.RaisePropertyChanged("Exitoso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExitosoSpecified {
            get {
                return this.exitosoFieldSpecified;
            }
            set {
                this.exitosoFieldSpecified = value;
                this.RaisePropertyChanged("ExitosoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("CodigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("MensajeError", IsNullable=true, Order=2)]
        public string[] MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("MensajeError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IdentificadorConsulta {
            get {
                return this.identificadorConsultaField;
            }
            set {
                this.identificadorConsultaField = value;
                this.RaisePropertyChanged("IdentificadorConsulta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Parametro", IsNullable=true, Order=4)]
        public Parametro[] Parametro {
            get {
                return this.parametroField;
            }
            set {
                this.parametroField = value;
                this.RaisePropertyChanged("Parametro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1658.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros")]
    public partial class ParametrosRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEspeciesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros")]
        public SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.Auditoria Auditoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.ParametrosRequest ParametrosRequest;
        
        public consultarEspeciesRequest() {
        }
        
        public consultarEspeciesRequest(SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.Auditoria Auditoria, SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.ParametrosRequest ParametrosRequest) {
            this.Auditoria = Auditoria;
            this.ParametrosRequest = ParametrosRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEspeciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ideam.gov.co/schema/snif/consultarparametros", Order=0)]
        public SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.ParametrosResponse ParametrosResponse;
        
        public consultarEspeciesResponse() {
        }
        
        public consultarEspeciesResponse(SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.ParametrosResponse ParametrosResponse) {
            this.ParametrosResponse = ParametrosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface snifconpar_pttChannel : SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.snifconpar_ptt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class snifconpar_pttClient : System.ServiceModel.ClientBase<SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.snifconpar_ptt>, SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.snifconpar_ptt {
        
        public snifconpar_pttClient() {
        }
        
        public snifconpar_pttClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public snifconpar_pttClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public snifconpar_pttClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public snifconpar_pttClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesResponse SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.snifconpar_ptt.consultarEspecies(SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesRequest request) {
            return base.Channel.consultarEspecies(request);
        }
        
        public SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.ParametrosResponse consultarEspecies(SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.Auditoria Auditoria, SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.ParametrosRequest ParametrosRequest) {
            SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesRequest inValue = new SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesRequest();
            inValue.Auditoria = Auditoria;
            inValue.ParametrosRequest = ParametrosRequest;
            SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.consultarEspeciesResponse retVal = ((SILPA.LogicaNegocio.WSConsultarEspeciesIDEAM.snifconpar_ptt)(this)).consultarEspecies(inValue);
            return retVal.ParametrosResponse;
        }
    }
}
