//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/ConsultaInscritosAudiencia.xsd")]
[System.Xml.Serialization.XmlRootAttribute("consultaInscritos", Namespace = "http://tempuri.org/ConsultaInscritosAudiencia.xsd", IsNullable = false)]
public partial class InscritosAudienciaConsultaType
{

    private string idInscritoField;

    private string nombreInscritoField;

    private string apellidoInscritoField;

    private string correoInscritoField;

    private string cedulaInscritoField;

    private string lugarExpedicionField;

    private string entidadComunidadField;

    private bool aprobadoInscritoField;

    private string motivoField;

    /// <comentarios/>
    public string IdInscrito
    {
        get
        {
            return this.idInscritoField;
        }
        set
        {
            this.idInscritoField = value;
        }
    }

    /// <comentarios/>
    public string NombreInscrito
    {
        get
        {
            return this.nombreInscritoField;
        }
        set
        {
            this.nombreInscritoField = value;
        }
    }

    /// <comentarios/>
    public string ApellidoInscrito
    {
        get
        {
            return this.apellidoInscritoField;
        }
        set
        {
            this.apellidoInscritoField = value;
        }
    }

    /// <comentarios/>
    public string CorreoInscrito
    {
        get
        {
            return this.correoInscritoField;
        }
        set
        {
            this.correoInscritoField = value;
        }
    }

    /// <comentarios/>
    public string CedulaInscrito
    {
        get
        {
            return this.cedulaInscritoField;
        }
        set
        {
            this.cedulaInscritoField = value;
        }
    }

    /// <comentarios/>
    public string LugarExpedicion
    {
        get
        {
            return this.lugarExpedicionField;
        }
        set
        {
            this.lugarExpedicionField = value;
        }
    }

    /// <comentarios/>
    public string EntidadComunidad
    {
        get
        {
            return this.entidadComunidadField;
        }
        set
        {
            this.entidadComunidadField = value;
        }
    }

    /// <comentarios/>
    public bool AprobadoInscrito
    {
        get
        {
            return this.aprobadoInscritoField;
        }
        set
        {
            this.aprobadoInscritoField = value;
        }
    }

    /// <comentarios/>
    public string Motivo
    {
        get
        {
            return this.motivoField;
        }
        set
        {
            this.motivoField = value;
        }
    }
}


